"I'm findin' ways to articulate the feelin' I'm goin' through",
"I just can't say I don't love you (Yeah)",
"'Cause I love you, yeah",
"It's hard for me to communicate the thoughts that I hold",
"But tonight, I'm gon' let you know",
"Let me tell the truth",
"Baby, let me tell the truth, yeah",
"You know what I'm thinkin', see it in your eyes",
"You hate that you want me, hate it when you cry",
"You're scared to be lonely, 'specially in the night",
"I'm scared that I'll miss you, happens every time",
"I don't want this feelin', I can't afford love",
"I try to find a reason to pull us apart",
"It ain't workin' 'cause you're perfect",
"And I know that you're worth it",
"I can't walk away, oh",
"Even though we're goin' through it",
"And it makes you feel alone",
"Just know that I would die for you",
"Baby, I would die for you, yeah",
"The distance and the time between us",
"It'll never change my mind 'cause",
"Baby, I would die for you",
"Baby, I would die for you, yeah (Say)",
"I'm findin' ways to manipulate the feelin' you're goin' through",
"But, baby girl, I'm not blamin' you",
"Just don't blame me, too, yeah",
"'Cause I can't take this pain forever",
"And you won't find no one that's better",
"'Cause I'm right for you, babe",
"I think I'm right for you, babe",
"You know what I'm thinkin', see it in your eyes",
"You hate that you want me, hate it when you cry",
"It ain't workin' 'cause you're perfect",
"And I know that you're worth it",
"I can't walk away, oh",
"Even though we're goin' through it",
"And it makes you feel alone",
"Just know that I would die for youDD",
"Baby, I would die for you, yeah",
"The distance and the time between us",
"It'll never change my mind 'cause",
"Baby, I would die for you, uh",
"Baby, I would die for you, yeah",
"I would die for you, I would lie for you",
"Keep it real with you, I would kill for you, my baby",
"I'm just sayin', yeah",
"I would die for you, I would lie for you",
"Keep it real with you, I would kill for you, my baby",
"Na-na-na, na-na-na, na-na-na",
"Even though we're goin' through it",
"And it makes you feel alone",
"Just know that I would die for you",
"Baby, I would die for you, yeah",
"The distance and the time between us",
"It'll never change my mind 'cause",
"Baby, I would die for you",
"Baby, I would die for you, yeah (Oh, babe)",
"(Die for you)",


b = [
    '"\r\n"',
    "\"I'm findin' ways to articulate the feelin' I'm goin' through\"",
    '",\r\n"',
    "\"I just can't say I don't love you (Yeah)\"",
    '",\r\n"',
    '"\'Cause I love you, yeah"',
    '",\r\n"',
    '"It\'s hard for me to communicate the thoughts that I hold"',
    '",\r\n"',
    "\"But tonight, I'm gon' let you know\"",
    '",\r\n"',
    '"Let me tell the truth"',
    '",\r\n"',
    '"Baby, let me tell the truth, yeah"',
    '",\r\n"',
    "\"You know what I'm thinkin', see it in your eyes\"",
    '",\r\n"',
    '"You hate that you want me, hate it when you cry"',
    '",\r\n"',
    "\"You're scared to be lonely, 'specially in the night\"",
    '",\r\n"',
    "\"I'm scared that I'll miss you, happens every time\"",
    '",\r\n"',
    "\"I don't want this feelin', I can't afford love\"",
    '",\r\n"',
    '"I try to find a reason to pull us apart"',
    '",\r\n"',
    "\"It ain't workin' 'cause you're perfect\"",
    '",\r\n"',
    '"And I know that you\'re worth it"',
    '",\r\n"',
    '"I can\'t walk away, oh"',
    '",\r\n"',
    "\"Even though we're goin' through it\"",
    '",\r\n"',
    '"And it makes you feel alone"',
    '",\r\n"',
    '"Just know that I would die for you"',
    '",\r\n"',
    '"Baby, I would die for you, yeah"',
    '",\r\n"',
    '"The distance and the time between us"',
    '",\r\n"',
    "\"It'll never change my mind 'cause\"",
    '",\r\n"',
    '"Baby, I would die for you"',
    '",\r\n"',
    '"Baby, I would die for you, yeah (Say)"',
    '",\r\n"',
    "\"I'm findin' ways to manipulate the feelin' you're goin' through\"",
    '",\r\n"',
    "\"But, baby girl, I'm not blamin' you\"",
    '",\r\n"',
    '"Just don\'t blame me, too, yeah"',
    '",\r\n"',
    "\"'Cause I can't take this pain forever\"",
    '",\r\n"',
    "\"And you won't find no one that's better\"",
    '",\r\n"',
    "\"'Cause I'm right for you, babe\"",
    '",\r\n"',
    '"I think I\'m right for you, babe"',
    '",\r\n"',
    "\"You know what I'm thinkin', see it in your eyes\"",
    '",\r\n"',
    '"You hate that you want me, hate it when you cry"',
    '",\r\n"',
    "\"It ain't workin' 'cause you're perfect\"",
    '",\r\n"',
    '"And I know that you\'re worth it"',
    '",\r\n"',
    '"I can\'t walk away, oh"',
    '",\r\n"',
    "\"Even though we're goin' through it\"",
    '",\r\n"',
    '"And it makes you feel alone"',
    '",\r\n"',
    '"Just know that I would die for youDD"',
    '",\r\n"',
    '"Baby, I would die for you, yeah"',
    '",\r\n"',
    '"The distance and the time between us"',
    '",\r\n"',
    "\"It'll never change my mind 'cause\"",
    '",\r\n"',
    '"Baby, I would die for you, uh"',
    '",\r\n"',
    '"Baby, I would die for you, yeah"',
    '",\r\n"',
    '"I would die for you, I would lie for you"',
    '",\r\n"',
    '"Keep it real with you, I would kill for you, my baby"',
    '",\r\n"',
    "\"I'm just sayin', yeah\"",
    '",\r\n"',
    '"I would die for you, I would lie for you"',
    '",\r\n"',
    '"Keep it real with you, I would kill for you, my baby"',
    '",\r\n"',
    '"Na-na-na, na-na-na, na-na-na"',
    '",\r\n"',
    "\"Even though we're goin' through it\"",
    '",\r\n"',
    '"And it makes you feel alone"',
    '",\r\n"',
    '"Just know that I would die for you"',
    '",\r\n"',
    '"Baby, I would die for you, yeah"',
    '",\r\n"',
    '"The distance and the time between us"',
    '",\r\n"',
    "\"It'll never change my mind 'cause\"",
    '",\r\n"',
    '"Baby, I would die for you"',
    '",\r\n"',
    '"Baby, I would die for you, yeah (Oh, babe)"',
    '",\r\n"',
    '"(Die for you)"',
    '","',
]

for i in b[0:15]:
    print(i)
